"""
Mood data for LumiiShift application.
Contains the comprehensive mood mapping with colors and messages.
"""

MOOD_MAP = {
    "happy": ("Yellow", "Bright and cheerful! 😄"),
    "angry": ("Red", "Fiery energy! 🔥"),
    "calm": ("Blue", "Relaxed and grounded. 🧘‍♂️"),
    "tired": ("Lavender", "Time to rest. 😴"),
    "focused": ("Green", "Sharp and alert. 🎯"),
    "sad": ("Teal", "Peace and balance. 😢"),
    "betrayed": ("DarkRed", "Deep emotional hurt. 💔"),
    "lonely": ("SlateBlue", "Solitude reflection. 🌌"),
    "confused": ("Violet", "Uncertainty and transition. 🤔"),
    "scared": ("DimGray", "Fear and caution. 😨"),
    "hopeful": ("MintCream", "Fresh optimism. 🌱"),
    "creative": ("Magenta", "Burst of imagination. 🎨"),
    "energetic": ("Cyan", "Full of energy! ⚡"),
    "confident": ("Gold", "Strength and pride. 🏆"),
    "nostalgic": ("SaddleBrown", "Looking back fondly. 🕰️"),
    "romantic": ("Pink", "Warmth and love. ❤️"),
    "playful": ("HotPink", "Fun and joy. 🐾"),
    "adventurous": ("Turquoise", "Time to explore! 🗺️"),
    "peaceful": ("SkyBlue", "Calm and serene. ☁️"),
    "moody": ("Charcoal", "Shifting emotions. 🌗"),
    "joyful": ("Orange", "Pure happiness. 🌻"),
    "excited": ("OrangeRed", "Eager anticipation! 🎉"),
    "determined": ("Crimson", "Driven and focused. 💪"),
    "anxious": ("Gray", "Stay steady. 😰"),
    "balanced": ("Beige", "Centering yourself. ⚖️"),
    "relaxed": ("Aqua", "Soothing calm. 🛁"),
    "optimistic": ("Lime", "Bright outlook. 🍋"),
    "inspired": ("Indigo", "Deep creativity. ✨"),
    "dreamy": ("Lavender", "Imagination flowing. 🌸"),
    "grateful": ("Olive", "Appreciation mindset. 🙏"),
    "guilty": ("Brown", "Reflect and learn. 🤎"),
    "jealous": ("DarkGreen", "Envy present. 😒"),
    "silly": ("DeepPink", "Whimsical fun. 🤪"),
    "hurt": ("Maroon", "Emotional pain. 😔"),
    "proud": ("RoyalBlue", "Achievement recognized. 🏅"),
    "awkward": ("Tan", "A little uncomfortable. 😳"),
    "restless": ("Silver", "Unsettled energy. ⚡"),
    "content": ("Ivory", "Quiet satisfaction. 🕊️"),
    "flirty": ("Coral", "Charming vibes. 😘"),
    "bored": ("Khaki", "Dull and unengaged. 😐"),
    "in_love": ("Crimson", "Heartfelt passion. 💖"),
    "overwhelmed": ("DarkGray", "Too much happening. 😵"),
    "motivated": ("DarkOrange", "Drive and energy. 🚀"),
    "fearless": ("DodgerBlue", "Bold courage. 🦁"),
    "curious": ("Goldenrod", "Eager to explore. 🧐"),
    "shy": ("LightPink", "Reserved charm. 🌸"),
    "gloomy": ("Navy", "Heavy heart. 🌑"),
    "grounded": ("SaddleBrown", "Stable and secure. 🌍"),
    "mystical": ("DarkMagenta", "Magical vibes. ✨"),
    "reflective": ("SlateGray", "Deep thinking. 🪨"),
    "eager": ("LimeGreen", "Ready for action! 🌱"),
    "serious": ("DarkBlue", "Focused and deep. 📘"),
    "passionate": ("DarkRed", "Intense emotion! ❤️‍🔥"),
    "thoughtful": ("DarkSeaGreen", "Wisdom and reflection. 🌿"),
    "uncertain": ("RosyBrown", "Doubt present. 🤷‍♂️"),
    "relieved": ("MediumSeaGreen", "Tension released. 🌱"),
    "overjoyed": ("Fuchsia", "Ecstatic happiness! 🥳")
}
